"""Phase 3 baseline path and provenance contracts."""

from __future__ import annotations

from importlib import import_module

from .evaluation import (
    BaselineEvaluationError,
    BaselineEvaluationFailure,
    BaselineEvaluationPublishError,
    BaselineEvaluationSerializationError,
    BaselineEvaluationValidationError,
    BaselinePredictionImportResult,
    build_reference_label_mapping_from_synthetic_fixture,
    import_saved_baseline_predictions,
    load_reference_label_mapping_artifact,
)
from .metrics import (
    BASELINE_CASE_METRICS_VERSION,
    BASELINE_LESION_CONNECTIVITY,
    BASELINE_METRIC_REPORT_VERSION,
    BASELINE_SURFACE_CONNECTIVITY,
    SUPPORTED_BASELINE_METRIC_FAMILIES,
    BaselineCaseMetrics,
    BaselineMetricAggregate,
    BaselineMetricError,
    BaselineMetricHashError,
    BaselineMetricReport,
    BaselineMetricSerializationError,
    BaselineMetricValidationError,
    BaselineMetricVersionError,
    baseline_case_metrics_from_json,
    baseline_case_metrics_to_json,
    baseline_metric_report_from_json,
    baseline_metric_report_to_json,
    build_baseline_metric_report,
    compute_baseline_case_metrics,
)
from .nnunet import (
    NNUNET_ALLOWED_INHERITED_ENVIRONMENT_KEYS,
    NNUNET_EXECUTION_FAILURE_CODES,
    NNUNET_V2_DEFAULT_CHECKPOINT_NAME,
    NNUNET_V2_DEFAULT_PLANNER,
    NNUNET_V2_DEFAULT_PLANS_IDENTIFIER,
    NNUNET_V2_DEFAULT_TRAINER,
    NNUNET_V2_EXECUTABLE_PLAN_AND_PREPROCESS,
    NNUNET_V2_EXECUTABLE_PREDICT,
    NNUNET_V2_EXECUTABLE_TRAIN,
    NNUNET_V2_RUN_CONFIG_VERSION,
    NNUNET_V2_SUPPORTED_CONFIGURATION,
    NNUNET_V2_SUPPORTED_DATASET_ID,
    NNUNET_V2_SUPPORTED_DEVICE,
    NNUNET_V2_SUPPORTED_FOLD,
    NnUNetExecutionError,
    NnUNetExecutionResult,
    NnUNetRuntimeEnvironment,
    NnUNetV2RunConfig,
    NnUNetWrapperError,
    NnUNetWrapperHashError,
    NnUNetWrapperSerializationError,
    NnUNetWrapperValidationError,
    NnUNetWrapperVersionError,
    build_nnunet_v2_plan_and_preprocess_command,
    build_nnunet_v2_predict_command,
    build_nnunet_v2_run_config,
    build_nnunet_v2_runtime_environment,
    build_nnunet_v2_train_command,
    execute_nnunet_command,
    nnunet_v2_run_config_from_json,
    nnunet_v2_run_config_to_json,
)
from .paths import (
    BASELINE_CHILD_DIRECTORY_NAMES,
    SUPPORTED_BASELINE_FAMILIES,
    BaselineFamily,
    BaselinePathError,
    BaselineRunRootConflictError,
    BaselineRunRootCreationError,
    InvalidBaselineRunRootError,
    ValidatedBaselineRunPaths,
    create_validated_run_directory_tree,
    validate_baseline_run_root,
    validate_non_overlapping_run_roots,
)
from .predictions import (
    BASELINE_PREDICTION_FOREGROUND_LABEL,
    BASELINE_PREDICTION_MANIFEST_VERSION,
    BASELINE_PREDICTION_RECORD_VERSION,
    SUPPORTED_BASELINE_PREDICTION_FAMILIES,
    BaselinePredictionError,
    BaselinePredictionHashError,
    BaselinePredictionManifest,
    BaselinePredictionRecord,
    BaselinePredictionSerializationError,
    BaselinePredictionValidationError,
    BaselinePredictionVersionError,
    baseline_prediction_manifest_from_json,
    baseline_prediction_manifest_to_json,
    build_baseline_prediction_manifest,
)
from .provenance import (
    BASELINE_RUN_PROVENANCE_VERSION,
    SUPPORTED_BASELINE_RUN_STATUSES,
    BaselineProvenanceError,
    BaselineProvenanceHashError,
    BaselineProvenanceSerializationError,
    BaselineProvenanceValidationError,
    BaselineProvenanceVersionError,
    BaselineRunProvenance,
    baseline_run_provenance_from_json,
    baseline_run_provenance_to_json,
)
from .synthetic import (
    BASELINE_SYNTHETIC_AFFINE,
    BASELINE_SYNTHETIC_DATASET_ID,
    BASELINE_SYNTHETIC_DATASET_NAME,
    BASELINE_SYNTHETIC_FILE_ENDING,
    BASELINE_SYNTHETIC_FIXTURE_VERSION,
    BASELINE_SYNTHETIC_SHAPE,
    BASELINE_SYNTHETIC_SPACING_MM,
    BASELINE_SYNTHETIC_TEST_CASE_IDENTIFIERS,
    BASELINE_SYNTHETIC_TRAINING_CASE_IDENTIFIERS,
    BaselineSyntheticFixtureArtifact,
    BaselineSyntheticFixtureError,
    BaselineSyntheticFixtureFileRecord,
    BaselineSyntheticFixtureGenerationResult,
    BaselineSyntheticFixtureHashError,
    BaselineSyntheticFixtureSerializationError,
    BaselineSyntheticFixtureValidationError,
    BaselineSyntheticFixtureVersionError,
    baseline_synthetic_fixture_from_json,
    baseline_synthetic_fixture_to_json,
    generate_baseline_synthetic_fixture,
    synthetic_affine_array,
    synthetic_cases,
    synthetic_dataset_json,
)

_LAZY_EXPORTS = {
    "MONAI_SEGRESNET_BASELINE_FAMILY": (
        "protoem_ct.baselines.monai_segresnet",
        "MONAI_SEGRESNET_BASELINE_FAMILY",
    ),
    "MONAI_SEGRESNET_DEFAULT_CHECKPOINT_NAME": (
        "protoem_ct.baselines.monai_segresnet",
        "MONAI_SEGRESNET_DEFAULT_CHECKPOINT_NAME",
    ),
    "MONAI_SEGRESNET_DEFAULT_SEED": (
        "protoem_ct.baselines.monai_segresnet",
        "MONAI_SEGRESNET_DEFAULT_SEED",
    ),
    "MONAI_SEGRESNET_RUN_CONFIG_VERSION": (
        "protoem_ct.baselines.monai_segresnet",
        "MONAI_SEGRESNET_RUN_CONFIG_VERSION",
    ),
    "MonaiSegResNetError": ("protoem_ct.baselines.monai_segresnet", "MonaiSegResNetError"),
    "MonaiSegResNetExecutionResult": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetExecutionResult",
    ),
    "MonaiSegResNetHashError": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetHashError",
    ),
    "MonaiSegResNetRunConfig": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetRunConfig",
    ),
    "MonaiSegResNetRuntimeError": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetRuntimeError",
    ),
    "MonaiSegResNetSerializationError": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetSerializationError",
    ),
    "MonaiSegResNetValidationError": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetValidationError",
    ),
    "MonaiSegResNetVersionError": (
        "protoem_ct.baselines.monai_segresnet",
        "MonaiSegResNetVersionError",
    ),
    "NNUNET_TINY_STRATEGY_IDENTIFIER": (
        "protoem_ct.baselines.nnunet_tiny",
        "NNUNET_TINY_STRATEGY_IDENTIFIER",
    ),
    "NnUNetTinyError": ("protoem_ct.baselines.nnunet_tiny", "NnUNetTinyError"),
    "NnUNetTinyExecutionResult": (
        "protoem_ct.baselines.nnunet_tiny",
        "NnUNetTinyExecutionResult",
    ),
    "NnUNetTinyRuntimeError": (
        "protoem_ct.baselines.nnunet_tiny",
        "NnUNetTinyRuntimeError",
    ),
    "PHASE3_GATE3_REPORT_VERSION": (
        "protoem_ct.baselines.gate3",
        "PHASE3_GATE3_REPORT_VERSION",
    ),
    "Phase3Gate3Error": ("protoem_ct.baselines.gate3", "Phase3Gate3Error"),
    "Phase3Gate3ExecutionResult": (
        "protoem_ct.baselines.gate3",
        "Phase3Gate3ExecutionResult",
    ),
    "Phase3Gate3HashError": ("protoem_ct.baselines.gate3", "Phase3Gate3HashError"),
    "Phase3Gate3Report": ("protoem_ct.baselines.gate3", "Phase3Gate3Report"),
    "Phase3Gate3SerializationError": (
        "protoem_ct.baselines.gate3",
        "Phase3Gate3SerializationError",
    ),
    "Phase3Gate3ValidationError": (
        "protoem_ct.baselines.gate3",
        "Phase3Gate3ValidationError",
    ),
    "Phase3Gate3VersionError": (
        "protoem_ct.baselines.gate3",
        "Phase3Gate3VersionError",
    ),
    "build_monai_segresnet_run_config": (
        "protoem_ct.baselines.monai_segresnet",
        "build_monai_segresnet_run_config",
    ),
    "build_phase3_gate3_report": (
        "protoem_ct.baselines.gate3",
        "build_phase3_gate3_report",
    ),
    "monai_segresnet_run_config_from_json": (
        "protoem_ct.baselines.monai_segresnet",
        "monai_segresnet_run_config_from_json",
    ),
    "monai_segresnet_run_config_to_json": (
        "protoem_ct.baselines.monai_segresnet",
        "monai_segresnet_run_config_to_json",
    ),
    "phase3_gate3_report_from_json": (
        "protoem_ct.baselines.gate3",
        "phase3_gate3_report_from_json",
    ),
    "phase3_gate3_report_to_json": (
        "protoem_ct.baselines.gate3",
        "phase3_gate3_report_to_json",
    ),
    "run_monai_segresnet_baseline": (
        "protoem_ct.baselines.monai_segresnet",
        "run_monai_segresnet_baseline",
    ),
    "run_nnunet_tiny_baseline": (
        "protoem_ct.baselines.nnunet_tiny",
        "run_nnunet_tiny_baseline",
    ),
    "run_phase3_gate3_synthetic": (
        "protoem_ct.baselines.gate3",
        "run_phase3_gate3_synthetic",
    ),
}


def __getattr__(name: str) -> object:
    """Lazily import heavy baseline modules to keep root imports light."""

    if name not in _LAZY_EXPORTS:
        raise AttributeError(name)
    module_name, attribute_name = _LAZY_EXPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attribute_name)
    globals()[name] = value
    return value


__all__ = [
    "BASELINE_CHILD_DIRECTORY_NAMES",
    "BASELINE_CASE_METRICS_VERSION",
    "BASELINE_LESION_CONNECTIVITY",
    "BASELINE_METRIC_REPORT_VERSION",
    "BASELINE_PREDICTION_FOREGROUND_LABEL",
    "BASELINE_PREDICTION_MANIFEST_VERSION",
    "BASELINE_PREDICTION_RECORD_VERSION",
    "BASELINE_RUN_PROVENANCE_VERSION",
    "BASELINE_SURFACE_CONNECTIVITY",
    "BASELINE_SYNTHETIC_AFFINE",
    "BASELINE_SYNTHETIC_DATASET_ID",
    "BASELINE_SYNTHETIC_DATASET_NAME",
    "BASELINE_SYNTHETIC_FILE_ENDING",
    "BASELINE_SYNTHETIC_FIXTURE_VERSION",
    "BASELINE_SYNTHETIC_SHAPE",
    "BASELINE_SYNTHETIC_SPACING_MM",
    "BASELINE_SYNTHETIC_TEST_CASE_IDENTIFIERS",
    "BASELINE_SYNTHETIC_TRAINING_CASE_IDENTIFIERS",
    "NNUNET_ALLOWED_INHERITED_ENVIRONMENT_KEYS",
    "NNUNET_EXECUTION_FAILURE_CODES",
    "NNUNET_V2_DEFAULT_CHECKPOINT_NAME",
    "NNUNET_V2_DEFAULT_PLANNER",
    "NNUNET_V2_DEFAULT_PLANS_IDENTIFIER",
    "NNUNET_V2_DEFAULT_TRAINER",
    "NNUNET_V2_EXECUTABLE_PLAN_AND_PREPROCESS",
    "NNUNET_V2_EXECUTABLE_PREDICT",
    "NNUNET_V2_EXECUTABLE_TRAIN",
    "NNUNET_V2_RUN_CONFIG_VERSION",
    "NNUNET_V2_SUPPORTED_CONFIGURATION",
    "NNUNET_V2_SUPPORTED_DATASET_ID",
    "NNUNET_V2_SUPPORTED_DEVICE",
    "NNUNET_V2_SUPPORTED_FOLD",
    "SUPPORTED_BASELINE_FAMILIES",
    "SUPPORTED_BASELINE_METRIC_FAMILIES",
    "SUPPORTED_BASELINE_PREDICTION_FAMILIES",
    "SUPPORTED_BASELINE_RUN_STATUSES",
    "BaselineCaseMetrics",
    "BaselineEvaluationError",
    "BaselineEvaluationFailure",
    "BaselineEvaluationPublishError",
    "BaselineEvaluationSerializationError",
    "BaselineEvaluationValidationError",
    "BaselineFamily",
    "BaselineMetricAggregate",
    "BaselineMetricError",
    "BaselineMetricHashError",
    "BaselineMetricReport",
    "BaselineMetricSerializationError",
    "BaselineMetricValidationError",
    "BaselineMetricVersionError",
    "BaselinePathError",
    "BaselinePredictionError",
    "BaselinePredictionHashError",
    "BaselinePredictionImportResult",
    "BaselinePredictionManifest",
    "BaselinePredictionRecord",
    "BaselinePredictionSerializationError",
    "BaselinePredictionValidationError",
    "BaselinePredictionVersionError",
    "BaselineProvenanceError",
    "BaselineProvenanceHashError",
    "BaselineProvenanceSerializationError",
    "BaselineProvenanceValidationError",
    "BaselineProvenanceVersionError",
    "BaselineRunProvenance",
    "BaselineRunRootConflictError",
    "BaselineRunRootCreationError",
    "BaselineSyntheticFixtureArtifact",
    "BaselineSyntheticFixtureError",
    "BaselineSyntheticFixtureFileRecord",
    "BaselineSyntheticFixtureGenerationResult",
    "BaselineSyntheticFixtureHashError",
    "BaselineSyntheticFixtureSerializationError",
    "BaselineSyntheticFixtureValidationError",
    "BaselineSyntheticFixtureVersionError",
    "InvalidBaselineRunRootError",
    "NnUNetExecutionError",
    "NnUNetExecutionResult",
    "NnUNetRuntimeEnvironment",
    "NnUNetV2RunConfig",
    "NnUNetWrapperError",
    "NnUNetWrapperHashError",
    "NnUNetWrapperSerializationError",
    "NnUNetWrapperValidationError",
    "NnUNetWrapperVersionError",
    "MONAI_SEGRESNET_BASELINE_FAMILY",
    "MONAI_SEGRESNET_DEFAULT_CHECKPOINT_NAME",
    "MONAI_SEGRESNET_DEFAULT_SEED",
    "MONAI_SEGRESNET_RUN_CONFIG_VERSION",
    "MonaiSegResNetError",
    "MonaiSegResNetExecutionResult",
    "MonaiSegResNetHashError",
    "MonaiSegResNetRunConfig",
    "MonaiSegResNetRuntimeError",
    "MonaiSegResNetSerializationError",
    "MonaiSegResNetValidationError",
    "MonaiSegResNetVersionError",
    "NNUNET_TINY_STRATEGY_IDENTIFIER",
    "NnUNetTinyError",
    "NnUNetTinyExecutionResult",
    "NnUNetTinyRuntimeError",
    "PHASE3_GATE3_REPORT_VERSION",
    "Phase3Gate3Error",
    "Phase3Gate3ExecutionResult",
    "Phase3Gate3HashError",
    "Phase3Gate3Report",
    "Phase3Gate3SerializationError",
    "Phase3Gate3ValidationError",
    "Phase3Gate3VersionError",
    "ValidatedBaselineRunPaths",
    "baseline_case_metrics_from_json",
    "baseline_case_metrics_to_json",
    "baseline_metric_report_from_json",
    "baseline_metric_report_to_json",
    "baseline_prediction_manifest_from_json",
    "baseline_prediction_manifest_to_json",
    "baseline_run_provenance_from_json",
    "baseline_run_provenance_to_json",
    "baseline_synthetic_fixture_from_json",
    "baseline_synthetic_fixture_to_json",
    "build_baseline_prediction_manifest",
    "build_nnunet_v2_plan_and_preprocess_command",
    "build_nnunet_v2_predict_command",
    "build_nnunet_v2_run_config",
    "build_nnunet_v2_runtime_environment",
    "build_nnunet_v2_train_command",
    "build_reference_label_mapping_from_synthetic_fixture",
    "build_baseline_metric_report",
    "build_monai_segresnet_run_config",
    "build_phase3_gate3_report",
    "compute_baseline_case_metrics",
    "create_validated_run_directory_tree",
    "execute_nnunet_command",
    "generate_baseline_synthetic_fixture",
    "import_saved_baseline_predictions",
    "load_reference_label_mapping_artifact",
    "monai_segresnet_run_config_from_json",
    "monai_segresnet_run_config_to_json",
    "nnunet_v2_run_config_from_json",
    "nnunet_v2_run_config_to_json",
    "phase3_gate3_report_from_json",
    "phase3_gate3_report_to_json",
    "run_monai_segresnet_baseline",
    "run_nnunet_tiny_baseline",
    "run_phase3_gate3_synthetic",
    "synthetic_affine_array",
    "synthetic_cases",
    "synthetic_dataset_json",
    "validate_baseline_run_root",
    "validate_non_overlapping_run_roots",
]
